live_config_reload = true

# Good dark theme: "~/.config/alacritty/themes/themes/catppuccin.toml"
# Good light theme: "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
import = [
    "~/.config/alacritty/themes/themes/catppuccin.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "MesloLGSDZ Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGSDZ Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGSDZ Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGSDZ Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = true

[window.padding]
x = 5
y = 5
