"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Scott Weber"
email = "scott@r45.ca"

[aliases]
# (From https://github.com/jj-vcs/jj/discussions/5812#discussioncomment-13095720)

# Some things to watch out for with jj aliases:
# - Keep them minimal; remain familiar with the builtin commands and defaults.
# - If they use -r, a command line -r will add to that, not override it.
# - If they use other options like -T or -n, those can't be overridden on the command line.

# log aliases. Most of these use -T and -n; the b and custom variants also use -r.
# All of them show graph structure; to hide it add --no-graph (can show confused output).

# "l" aliases: list recent changes on multiple branches, elided, as one line.
# add more l's to show more changes: l=10, ll=30, lll=100, llll=all
l           = ["log", "-Tlog1", "-n25"]
ll          = ["log", "-Tlog1"]

# append a for "all()", as log defaults to local commits only
la          = ["log", "-Tlog1", "-r", "all()", "-n25"]
lla         = ["log", "-Tlog1", "-r", "all()"]

# append v to show full descriptions
lv          = ["log", "-Tlogv", "-n25"]
llv         = ["log", "-Tlogv"]

# prepend b to show current branch only, non-elided
bl          = ["log", "-Tlog1", "-r::@", "-n25"]
bll         = ["log", "-Tlog1", "-r::@"]

blv         = ["log", "-Tlogv", "-r::@", "-n25"]
bllv        = ["log", "-Tlogv", "-r::@"]

# "log" aliases: other custom change lists, using the default template (builtin_log_compact)
#log                                                          # default log view: trunk and unmerged/unpushed branches, as two lines
logconflicts = ["log", "-r", "conflicts()"]                   # conflicting commits
lognew       = ["log", "-r", "(master..@):: | (master..@)-"]  # commits since master in current branch
logpush      = ["log", "-r", "trunk()::@"]                    # unpushed to origin in current branch
logpull      = ["log", "-r", "@..trunk()"]                    # unpulled from origin in current branch
logpullall   = ["log", "-r", "@-..remote_bookmarks()"]        # unpulled from all remotes in current branch

# op log
o          = ["op", "log"]                                      # all operations
oo         = ["op", "log", "-T", "builtin_op_log_comfortable"]  # all operations, with more whitespace

[template-aliases]
# (From https://github.com/jj-vcs/jj/discussions/5812#discussioncomment-13095720)
# Additional templates and helpers.
# log templates. Most of these use my smlog() layout.
# Author's name, committer's timestamp and time zone, full descriptions.
logv = 'smlog(original_time(committer.timestamp()), description, bookmarks, tags)'
# Like logv but just one line of description.
log1 = 'smlog(original_time(committer.timestamp()), description.first_line(), bookmarks, tags)'

# helpers:
'local_time(timestamp)'       = 'timestamp.local().format("%Y-%m-%d %H:%M:%S")'
'localised_time(timestamp)'   = 'timestamp.local().format("%Y-%m-%d %H:%M:%S %z")'
'original_time(timestamp)'    = 'timestamp.format("%Y-%m-%d %H:%M:%S %z")'

# Generate a log template with a more aligned layout for readability:
# both hashes and other fixed width fields on the left,
# bookmarks and tags displayed optionally (used by jjbookmarks, jjtags),
# bookmarks enclosed in brackets to distinguish them from tags,
# description starting on the same line.
'smlog(timestr, description, bookmarks, tags)' = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      separate(" ",
        format_short_change_id_with_hidden_and_divergent_info(self),
        format_short_commit_id(commit_id),
        timestr,
        if(author.email(), author.email().local(), email_placeholder),
        if(bookmarks,surround("[","]",bookmarks),""),
        tags,
        working_copies,
        if(git_head, label("git_head", "git_head()")),
        if(conflict, label("conflict", "conflict")),
        if(empty, label("empty", "(empty)")),
        if(description,
          description,
          label(if(empty, "empty"), description_placeholder),
        ),
      ) ++ "\n",
    ),
  )
)
'''
