# agent.sh fish completion loader (auto-generated by agent.sh install-fish)
function __agent_in_jj_repo
    command jj root >/dev/null 2>/dev/null
end

function __agent_in_managed_workspace
    set -l script "/home/sweber/.dotfiles/bin/agent.sh"
    test -x "$script"; and command "$script" parent-root >/dev/null 2>/dev/null
end

function __agent_existing_workspaces
    command jj workspace list --template 'name ++ "\n"' 2>/dev/null
end

  set -l __agent_subcommands codex claude fish switch artifacts cleanup status help
  set -l __agent_artifact_actions status enable disable opt-in opt-out clean

complete -c agent -f -n "not __fish_seen_subcommand_from $__agent_subcommands; and __agent_in_jj_repo" -a artifacts -d "Manage artifact hydration"
complete -c agent -f -n "not __fish_seen_subcommand_from $__agent_subcommands" -a codex -d "Create workspace and launch Codex"
complete -c agent -f -n "not __fish_seen_subcommand_from $__agent_subcommands" -a claude -d "Create workspace and launch Claude Code"
complete -c agent -f -n "not __fish_seen_subcommand_from $__agent_subcommands" -a fish -d "Create workspace and switch to it"
complete -c agent -f -n "not __fish_seen_subcommand_from $__agent_subcommands" -a switch -d "Switch to an existing workspace"
complete -c agent -f -n "not __fish_seen_subcommand_from $__agent_subcommands; and __agent_in_jj_repo" -a cleanup -d "Forget and delete a managed workspace"
complete -c agent -f -n "not __fish_seen_subcommand_from $__agent_subcommands; and __agent_in_jj_repo" -a status -d "Show JJ workspace status"
complete -c agent -f -n "not __fish_seen_subcommand_from $__agent_subcommands" -a help -d "Show help"
complete -c agent -f -n "__fish_seen_subcommand_from status" -l compact -d "Compact status output"
complete -c agent -f -n "__fish_seen_subcommand_from status" -l no-color -d "Disable color in status output"
complete -c agent -f -n "__fish_seen_subcommand_from artifacts; and test (count (commandline -opc)) -eq 3" -a "$__agent_artifact_actions"

complete -c agent -f -n "__fish_seen_subcommand_from codex claude fish switch cleanup; and test (count (commandline -opc)) -eq 2" -a "(__agent_existing_workspaces)"
complete -c agent -f -n "__fish_seen_subcommand_from artifacts; and test (count (commandline -opc)) -eq 4" -a "(__agent_existing_workspaces)"
