# syntax=toml
#
# Example configuration for Paneru.
# Docs here: https://github.com/karinushka/paneru/blob/main/CONFIGURATION.md
#

[options]
# Enables focus follows mouse. Enabled by default, set to false to disable.
# focus_follows_mouse = true

# Enables mouse follows focus. Enabled by default, set to false to disable.
# mouse_follows_focus = true

# Array of widths used by the `window_resize` action to cycle between.
# Defaults to 25%, 33%, 50%, 66% and 75%.
preset_column_widths = [ 0.25, 0.33, 0.50, 0.66, 0.75, 1.0 ]

# Window movement speed in pixels/second.
# To disable animations, leave this unset or set to a very large value.
animation_speed = 20

# If enabled, a virtual workspace without any windows will be removed.
#reap_empty_workspaces = true


[swipe]
# Swiping the windows left and right will keep sliding them until the first or
# last window. Set to false to always keep the current window on screen and
# fully exposed. Enabled by default.
continuous = false
deceleration = 10.0

[swipe.gesture]
# How many fingers to use for moving windows left and right.
# Make sure that it doesn't clash with OS setting for workspace switching.
# Values lower than 3 will be ignored.
# Remove the line to disable the gesture feature.
# Apple touchpads support gestures with more than five fingers (!),
# but it is probably not that useful to use two hands :)
fingers_count = 3


[decorations] 
# hide buggy virtual workspace popup indicator
workspace_popup_status = false

[decorations.inactive.dim]
opacity = -0.10
opacity_night = -0.05


[bindings]
# Moves the focus between windows.
window_focus_west = "alt - h"
window_focus_east = "alt - l"
window_focus_north = "alt - k"
window_focus_south = "alt - j"

# Swaps windows in chosen direction.
window_swap_west = "alt + ctrl - h"
window_swap_east = "alt + ctrl - l"
window_swap_north = "alt + ctrl - k"
window_swap_south = "alt + ctrl - j"

# Jump to the left-most or right-most windows.
window_focus_first = "alt - home"
window_focus_last = "alt - end"

# Move the current window into the left-most or right-most positions.
window_swap_first = "alt + ctrl - home"
window_swap_last = "alt + ctrl - end"

# Centers the current window on screen.
window_center = "alt - c"

# Cycles between the window sizes defined in the `preset_column_widths` option.
window_resize = "alt - r"
window_grow = "alt - ="
window_shrink = "alt - minus"

# Toggle full width for the current focused window.
window_fullwidth = "alt - f"

# Toggles the window for management. If unmanaged, the window will be "floating".
window_manage = "alt - v"

# Stacks and unstacks a window into the left column. Each window gets a 1/N of the height.
window_stack = "alt - ,"
window_unstack = "alt - ."

# Virtual desktops
window_virtual_north = "alt - i"
window_virtual_south = "alt - u"
window_virtualmove_north = "ctrl + alt - i"
window_virtualmove_south = "ctrl + alt - u"
window_virtualnum_1 = "alt - 1"
window_virtualnum_2 = "alt - 2"
window_virtualnum_3 = "alt - 3"
window_virtualnum_4 = "alt - 4"
window_virtualnum_5 = "alt - 5"
window_virtualnum_6 = "alt - 6"
window_virtualnum_7 = "alt - 7"
window_virtualnum_8 = "alt - 8"
window_virtualnum_9 = "alt - 9"
window_virtualmovenum_1 = "alt + ctrl - 1"
window_virtualmovenum_2 = "alt + ctrl - 2"
window_virtualmovenum_3 = "alt + ctrl - 3"
window_virtualmovenum_4 = "alt + ctrl - 4"
window_virtualmovenum_5 = "alt + ctrl - 5"
window_virtualmovenum_6 = "alt + ctrl - 6"
window_virtualmovenum_7 = "alt + ctrl - 7"
window_virtualmovenum_8 = "alt + ctrl - 8"
window_virtualmovenum_9 = "alt + ctrl - 9"

# Snap an overflowing window into the viewport
window_snap = "alt - s"

# Moves currently focused window to another display.
window_nextdisplay = "alt - n"

# Quits the window manager.
quit = "ctrl + alt - q"

# Window properties, matched by a RegExp title string.
[windows]

[windows.pip]
# Title RegExp pattern is required.
title = "Picture.*(in)?.*[Pp]icture"
# Do not manage this window, e.g. it will be floating.
floating = true

[windows.settings]
title = "System.*Settings"
floating = true

[windows.all]
# Matches all windows and adds a few pixels of spacing to their borders.
title = ".*"
horizontal_padding = 4
vertical_padding = 4
