# agent.sh fish loader (auto-generated by agent.sh install-fish)
function agent --description "Manage jj workspaces for coding agents"
    set -l script "/home/sweber/.dotfiles/bin/agent.sh"

    if test ! -x "$script"
        echo "agent: missing executable $script" >&2
        return 1
    end

    if test (count $argv) -ge 1
        if contains -- "$argv[1]" codex claude
            if test (count $argv) -lt 2
                echo "agent: missing workspace name for $argv[1]" >&2
                return 1
            end

            set -l workspace_dir (command "$script" prepare-workspace "$argv[2]")
            set -l prepare_status $status
            if test $prepare_status -ne 0
                return $prepare_status
            end

            cd "$workspace_dir"
            command "$argv[1]" $argv[3..-1]
            return $status
        end

        if test "$argv[1]" = "fish"
            if test (count $argv) -lt 2
                echo "agent: missing workspace name for $argv[1]" >&2
                return 1
            end

            set -l workspace_dir (command "$script" prepare-workspace "$argv[2]")
            set -l prepare_status $status
            if test $prepare_status -ne 0
                return $prepare_status
            end

            cd "$workspace_dir"
            return $status
        end

        if test "$argv[1]" = "switch"
            set -l workspace_dir (command "$script" switch-target $argv[2..-1])
            set -l switch_status $status
            if test $switch_status -ne 0
                return $switch_status
            end

            cd "$workspace_dir"
            return $status
        end

        if test "$argv[1]" = "cleanup"
            set -l parent (command "$script" parent-root 2>/dev/null)
            set -l cwd_before (pwd -P)
            env AGENT_SUPPRESS_PARENT_NOTE=1 "$script" $argv
            set -l exit_code $status

            if test $exit_code -eq 0; and test ! -d "$cwd_before"; and test -n "$parent"; and test -d "$parent"
                cd "$parent"
            end

            return $exit_code
        end
    end

    command "$script" $argv
end
